### ISSUE TITLE
tl_teaser & dateAdded (copy & paste error)?

### ISSUE THREAD

**Issue by fritzmg** [srhinow/themecontent-bundle#1]
Creating a new theme content section is not possible, since it ends with an SQL error saying that the table `tl_teaser` does not exist. The SQL update is being done here: https://github.com/srhinow/themecontent-bundle/blob/0.1.9/src/Resources/contao/dca/tl_theme_section.php#L687-L710

However, neither `tl_teaser` nor the field `dateAdded` is defined anywhere in this extension. Is this a copy & paste error may be?

**Comment by srhinow** [comment]
yes this was a copy&paste error. Sorry i had only sql-import before
