### ISSUE TITLE
insert_theme_content

### ISSUE THREAD

**Issue by theDyingMountain** [srhinow/themecontent-bundle#7]
Ein weiterer Tag für Content `insert_theme_content` wäre noch sehr nützlich. Habe ich schon auskommentiert im Code gesehen ;)

**Comment by srhinow** [comment]
Aber du kannst doch das ganz normale insert_content nehmen da dies die gleiche Tabelle und Logik nutzt wie alle anderen auf tl_content basierenden Module (Artikel,News etc.) Das steht im Code da ich damals wohl noch nen Denkfehler hatte und dann das {{insert_content::xx}} erfolgreich ausprobiert hatte. ;)

**Comment by theDyingMountain** [comment]
Alles klar danke 😃
