### ISSUE TITLE
Erweiterung kann nicht installiert werden

### ISSUE THREAD

**Issue by designpilot** [srhinow/themecontent-bundle#8]
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
 
  Problem 1
    - cliffparnitzky/tiny-mce-bundle-all 2.10.0 requires contao/core >=3.3.0,<3.6 -> satisfiable by contao/core[3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.28, 3.5.29, 3.5.3, 3.5.30, 3.5.31, 3.5.32, 3.5.33, 3.5.34, 3.5.35, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - contao/core 3.4.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.10 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.11 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.12 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.13 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.14 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.15 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.16 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.17 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.18 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.19 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.20 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.21 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.22 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.23 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.24 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.25 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.26 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.27 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.28 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.29 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.30 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.31 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.32 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.33 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.34 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.35 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.6 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.7 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.8 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.9 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - cliffparnitzky/tiny-mce-bundle-all 2.10.1 requires cliffparnitzky/tiny-mce-anchor ~1.1 -> no matching package found.
    - contao/core 3.3.7 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.6 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.5 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.4 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.3 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.2 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.1 requires contao/idna 0.8.1.1 -> no matching package found.
    - contao/core 3.3.0 requires contao/idna 0.8.1.1 -> no matching package found.
    - Installation request for contao/managed-edition No version set (parsed as 1.0.0) -> satisfiable by contao/managed-edition[No version set (parsed as 1.0.0)].
    - Installation request for cliffparnitzky/tiny-mce-bundle-all ^2.10 -> satisfiable by cliffparnitzky/tiny-mce-bundle-all[2.10.0, 2.10.1].
 
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
 
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
Finished Composer Cloud resolving.

**Comment by fritzmg** [comment]
This has nothing to do with this package. Please post your problem on the Contao community forum.

**Comment by srhinow** [comment]
diese Erweiterung ist für Vontao 4.4 und höher aber nicht für Contao 3.5.x
